---

- hosts: all
  become: yes
  vars:
    dotfile_repo_path: git@github.com:ProgrammingAce/dotfiles.git
  tasks:
    - name: Install software
      yum:
        name={{ item }}
        state=latest
        enablerepo=epel
      with_items:
        - tree
        - git
        - dstat
        - nmap
        - curl
        - wget
        - vim-enhanced
        - python-pip
        - python-simplejson
        - ansible
        - ansible-lint
        - irssi
        - "@Development tools"
